# https://hub.docker.com/_/tomcat
# https://github.com/docker-library/docs/blob/master/tomcat/README.md#supported-tags-and-respective-dockerfile-links
# https://tomcat.apache.org/whichversion.html
FROM tomcat:9.0

EXPOSE 8009